server:
  port: 8082
  error:
    include-message: always
spring:
#  cloud:
#    consul:
#      host: http://consul
#      port: 8500
  application:
    name: users
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: bebright
      port: 27017
#      host: mongodb
#      uri: mongodb://rootuser:rootpass@mongodb:27017/bebright
      auto-index-creation: true
jwt:
  secret: secretkey #TODO: secret key should be encrypted
  token:
    validity: 180000 #3 minutes validity
