server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
#        ROUTES FOR USER SERVICE
        - id: users-sign-in
          uri: lb://USERS
          predicates:
            - Path=/login
        - id: register-user
          uri: lb://USERS
          predicates:
            - Path=/register
        - id: refresh-token
          uri: lb://USERS
          predicates:
            - Path=/token/refresh
        - id: users-protected
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - CustomAuthorisationFilter

#       POST ROUTES
        - id: posts-protected
          uri: lb://POSTS
          predicates:
            - Path=/posts/**

#         ROUTES FOR INTEREST SERVICE
        - id: interests-protected
          uri: lb://INTERESTS
          predicates:
            - Path=/interests/**
          filters:
            - CustomAuthorisationFilter
#  cloud:
#    consul:
#      host: http://consul
#      port: 8500