server:
  port: 8086
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-sign-in
          uri: lb://USERS
          predicates:
            - Path=/users/signIn
        - id: users-by-office
          uri: lb://USERS
          predicates:
            - Path=/users/getUsersByOffice/**
          filters:
            - AuthenticationFilter
        - id: users-by-office-and-team
          uri: lb://USERS
          predicates:
            - Path=/users/getUsersByOfficeAndTeam/**
          filters:
            - AuthenticationFilter
        - id: register-user
          uri: lb://USERS
          predicates:
            - Path=/users/registerNewUser
#  cloud:
#    consul:
#      host: http://consul
#      port: 8500