server:
  port: 8086
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-sign-in
          uri: lb://USERS
          predicates:
            - Path=/login
        - id: users-protected
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: register-user
          uri: lb://USERS
          predicates:
            - Path=/register
#  cloud:
#    consul:
#      host: http://consul
#      port: 8500