server:
  port: 8086
spring:
#  cloud:
#    consul:
#      host: http://consul
#      port: 8500
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: users
#            uri: lb://USERS
#            predicates:
#              - Path=/user/**