server:
  port: 8083
  error:
    include-message: always
spring:
  #  cloud:
  #    consul:
  #      host: http://consul
  #      port: 8500
  application:
    name: posts
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: bebright
      port: 27017
      #      host: mongodb
      #      uri: mongodb://rootuser:rootpass@mongodb:27017/bebright
      auto-index-creation: true
